# vim: set ft=ruby:
# frozen_string_literal: true

personal = 'Pyra'
work = 'Haze'

hostname = `scutil --get ComputerName`.chomp

tap 'starkwm/formulae'
tap 'tombell/formulae'

brew 'bat'
brew 'fd'
brew 'fzf'
brew 'mole'
brew 'rcm'
brew 'ripgrep'
brew 'starkwm/formulae/skbd@2'
brew 'starkwm/formulae/swm'
brew 'zoxide'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'

cask '1password-cli'
cask '1password@nightly'
cask 'appcleaner'
cask 'ghostty@tip'
cask 'keka'
cask 'keyboardcleantool'

if [personal, work].include? hostname
  brew 'gh'
  brew 'git'
  brew 'git-delta'
  brew 'jj'
  brew 'jq'
  brew 'libpq'
  brew 'libyaml'
  brew 'mas'
  brew 'mise'
  brew 'tmux'
  brew 'tree'
  brew 'xz'

  cask 'daisydisk'
  cask 'discord'
  cask 'tombell/formulae/font-iosevka-custom'
  cask 'google-chrome'
  cask 'postico'
  cask 'soundsource'
  cask 'telegram'

  mas 'Xcode', id: 497_799_835
end

if [personal].include? hostname
  brew 'ollama'
  brew 'transmission-cli'

  cask 'codex'
  cask 'codex-app'
  cask 'handy'
  cask 'rekordbox'
end

if [work].include? hostname
  brew 'cloudflared'
  brew 'mailpit'
  brew 'postgresql@18'
  brew 'railway'
  brew 'redis'
  brew 'tombell/formulae/tmux-manager'

  cask 'claude'
  cask 'claude-code@latest'
  cask 'linear'
  cask 'mac-mouse-fix'
end
