# vim: set ft=ruby:
# frozen_string_literal: true

personal = 'Pyra'
work = 'Haze'
agent = 'Brighid'

hostname = `scutil --get ComputerName`.chomp

tap 'conjuror-app/tap', trusted: true
tap 'starkwm/formulae', trusted: true
tap 'tombell/formulae', trusted: true

brew 'bat'
brew 'fd'
brew 'fish'
brew 'fzf'
brew 'mole'
brew 'rcm'
brew 'ripgrep'
brew 'zoxide'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'

cask '1password-cli'
cask '1password@nightly'
cask 'appcleaner'
cask 'ghostty@tip'
cask 'keka'

if [personal, work, agent].include? hostname
  brew 'gh'
  brew 'git'
  brew 'git-delta'
  brew 'herdr'
  brew 'jj'
  brew 'jq'
  brew 'libyaml'
  brew 'mas'
  brew 'mise'
  brew 'tombell/formulae/codex-sync', args: ['HEAD']
  brew 'tombell/formulae/tendr', args: ['HEAD']

  cask 'codex'
  cask 'daisydisk'
  cask 'tombell/formulae/font-iosevka-custom'
  cask 'google-chrome'
  cask 'tailscale-app'

  mas 'Xcode', id: 497_799_835
end

if [personal, work].include? hostname
  brew 'starkwm/formulae/skbd@2'
  brew 'starkwm/formulae/swm'

  cask 'conjuror-app/tap/conjuror@alpha'
  cask 'discord'
  cask 'keyboardcleantool'
  cask 'postico'
  cask 'soundsource'
  cask 'telegram'
end

if [personal].include? hostname
  cask 'chatgpt'
  cask 'rekordbox'
end

if [work].include? hostname
  brew 'cloudflared'
  brew 'libpq'
  brew 'mailpit'
  brew 'postgresql@18'
  brew 'railway'
  brew 'redis'

  cask 'claude'
  cask 'claude-code@latest'
  cask 'linear'
  cask 'mac-mouse-fix'
end

if [agent].include? hostname
  brew 'ffmpeg'
  brew 'imagemagick'
  brew 'transmission-cli'

  cask 'hermes-desktop'
end
